### PR TITLE
fix: jsonRespository.DoCache does not hang when redisjson  module is not installed

### LINKED ISSUE #591: Sample code for Generic Object Mapping hangs indefinitely
### Bug
Running sample code from https://github.com/redis/rueidis/tree/main/om#generic-object-mapping using a `JSONRepository` causes the repo to hang indefinitely.

### Initial findings
`singleClient` gets stuck at `DoCache` operation:
```go
func (c *singleClient) DoCache(ctx context.Context, cmd Cacheable, ttl time.Duration) (resp RedisResult) {
retry:
	resp = c.conn.DoCache(ctx, cmd, ttl)
	if c.retry && c.isRetryable(resp.NonRedisError(), ctx) {
		goto retry // <-- execution falls here
	}
	if err := resp.NonRedisError(); err == nil || err == ErrDoCacheAborted {
		cmds.PutCacheable(cmd)
	}
	return resp
}
```
Returned error:
> "failed to fetch the cache because EXEC was aborted by redis or connection closed"

### Steps to reproduce:
- Start a redis server locally by running `redis-server` on terminal
- Copy sample code from https://github.com/redis/rueidis/tree/main/om#generic-object-mapping onto a `main.go` file
- Replace `NewHashRepository` with `NewJSONRepository`
- Run code: `go run main.go`

### Expected result
Program executes through completion without hanging.

### Environment
- **OS**: Linux matheus 6.5.0-44-generic # 44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jun 18 14:36:16 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- **go version**: go version go1.21.6 linux/amd64
- **Redis version**: Redis server v=7.2.5 sha=00000000:0 malloc=jemalloc-5.3.0 bits=64 build=d284576ab9ca3cc5
- **rueidis version**: v1.0.41

### PR DESCRIPTION
**Pull request by ajayd-san**
Hey, 

This fixes #591

Let me know if i have to add anything else.

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -248,7 +248,7 @@ func (c *dedicatedSingleClient) release() {
 }
 
 func (c *singleClient) isRetryable(err error, ctx context.Context) bool {
-	return err != nil && atomic.LoadUint32(&c.stop) == 0 && ctx.Err() == nil
+	return err != nil && atomic.LoadUint32(&c.stop) == 0 && ctx.Err() == nil && err != ErrDoCacheAborted
```
Comment (rueian) [inline client.go:251]: Hi @ajayd-san, thanks! Could you change the order of the new check? Move it to the in front of the atomic.LoadUint32.

Comment (ajayd-san) [reply client.go]: Done!
